"""Add manual balance fields to User

Revision ID: 58f14c2f3d57
Revises: 2538d02bb92f
Create Date: 2025-09-21 11:46:57.441042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f14c2f3d57'
down_revision = '2538d02bb92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trivia_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('youtube_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_balance')
        batch_op.drop_column('youtube_balance')
        batch_op.drop_column('trivia_balance')
        batch_op.drop_column('referral_balance')

    # ### end Alembic commands ###
