"""Add TriviaAnswer model

Revision ID: 82c3b8704151
Revises: 3ea5b6ddbc4b
Create Date: 2025-09-16 17:50:20.531723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c3b8704151'
down_revision = '3ea5b6ddbc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.alter_column('earned',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.alter_column('earned',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
