"""Add referral columns to user

Revision ID: 962129fe3db4
Revises: 
Create Date: 2025-09-24 15:38:28.378065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962129fe3db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_code', sa.String(length=50), nullable=False, server_default='UNKNOWN'))
    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('referred_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('referrer_username', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['referred_by'], ['id'])
        batch_op.drop_column('today_whatsapp_balance')
        batch_op.drop_column('today_spin_balance')
        batch_op.drop_column('today_youtube_balance')
        batch_op.drop_column('today_referral_balance')
        batch_op.drop_column('today_trivia_balance')
        batch_op.drop_column('wallet_reset_date')

    with op.batch_alter_table('whats_app_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('views_left', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('earnings_per_view', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whats_app_post', schema=None) as batch_op:
        batch_op.drop_column('earnings_per_view')
        batch_op.drop_column('views_left')
        batch_op.drop_column('total_views')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_reset_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('today_trivia_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('today_referral_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('today_youtube_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('today_spin_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('today_whatsapp_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('referrer_username')
        batch_op.drop_column('referred_by')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('trivia_answer', schema=None) as batch_op:
        batch_op.drop_column('correct')
        batch_op.drop_column('answer')
        batch_op.drop_column('question_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('mpesa_code')

    # ### end Alembic commands ###
