"""Add created_at to Payment and clean models

Revision ID: d54e75a82805
Revises: f5aa3465725b
Create Date: 2025-09-16 13:41:20.926126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54e75a82805'
down_revision = 'f5aa3465725b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
