"""Add today's manual earnings columns to User

Revision ID: f1ed2d8e457a
Revises: 962129fe3db4
Create Date: 2025-09-24 16:43:14.449672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ed2d8e457a'
down_revision = '962129fe3db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_today_manual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('trivia_today_manual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('youtube_today_manual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_today_manual', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_today_manual')
        batch_op.drop_column('youtube_today_manual')
        batch_op.drop_column('trivia_today_manual')
        batch_op.drop_column('referral_today_manual')

    # ### end Alembic commands ###
