"""Add referrer_username column

Revision ID: f5aa3465725b
Revises: 6ec9f0c0508a
Create Date: 2025-09-16 03:34:29.119892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5aa3465725b'
down_revision = '6ec9f0c0508a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_username', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referrer_username')

    # ### end Alembic commands ###
